apiVersion: v1
kind: Secret
metadata:
  name: school-secrets
  labels:
    app: school-mgmt
type: Opaque
data:
  # echo -n "your-password" | base64
  db-password: Y2hhbmdlbWU=
  # echo -n "your-jwt-secret" | base64
  jwt-secret: Y2hhbmdlbWU=
  # echo -n "smtp-user@example.com" | base64
  mail-username: Y2hhbmdlbWU=
  # echo -n "smtp-password" | base64
  mail-password: Y2hhbmdlbWU=
